### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by i-max-xi** [mnekx/ibhichekesho#3]
This is a peer to peer review of code.
We can all add out comments here

**Comment by i-max-xi** [comment]
It is always a good idea to add a screenshot of the hero section or otherwise known as the welcome page to the README file

**Comment by zmekonnen251** [comment]
- You did an amazing job so far. I see you add the footer and partners section on the home page of the mobile version. There is no footer and partners section in the requirement. I think it is good to follow the requirement. 👍

**Comment by Mutalenic** [comment]
- The images in the speaker section would look clearer if you resize the height.
- The header text would look better if you reduced the font to 30px

**Comment by mnekx** [comment]
Thanks guys for good inputs, I will surely work on these.
